<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>2025.10</AssemblyVersion>
    <FileVersion>2025.10</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adastral.Cockatoo.Services.WebApi\Adastral.Cockatoo.Services.WebApi.csproj" />
    <ProjectReference Include="..\Adastral.Cockatoo.Shared.AspNet\Adastral.Cockatoo.Common.AspNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Extensions.Logging" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.10" />
  </ItemGroup>

</Project>
