<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adastral.Cockatoo.Services.WebApi.Models\Adastral.Cockatoo.Services.WebApi.Models.csproj" />
      <ProjectReference Include="..\Adastral.Cockatoo.Services\Adastral.Cockatoo.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Sentry.AspNetCore" Version="5.16.2" />
      <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="3.6.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>

</Project>
