<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Adastral.Cockatoo.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adastral.Cockatoo.Common\Adastral.Cockatoo.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
  </ItemGroup>
</Project>
